- name: install httpd
  yum: name=httpd state=latest
- name: copy index.html
  template:
    src: index.j2
    dest: /var/www/html/index.html
  notify:
    - restart httpd
- name: start httpd
  service: name=httpd state=started
